/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.vendingMachine;


import javax.swing.JOptionPane;
import static my.vendingMachine.VendingMachineFrame.*;

/**
 *
 * @author ryan3
 */
public class AddMoneyFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddMoneyFrame
     */
    public AddMoneyFrame() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2EuroStockA = new javax.swing.JButton();
        jTextField2EuroS = new javax.swing.JTextField();
        jButton1EuroStock1A = new javax.swing.JButton();
        jTextField1EuroS = new javax.swing.JTextField();
        jButton50CentStockA = new javax.swing.JButton();
        jTextField50CentS = new javax.swing.JTextField();
        jButton20CentStockA = new javax.swing.JButton();
        jTextField20CentS = new javax.swing.JTextField();
        jButtonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1EuroStockM = new javax.swing.JButton();
        jButton50CentStockM = new javax.swing.JButton();
        jButton20CentStockM = new javax.swing.JButton();
        jButton2EuroStockM = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton10CentStockA = new javax.swing.JButton();
        jTextField10CentS = new javax.swing.JTextField();
        jButton10CentStockM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddMoney");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton2EuroStockA.setText("+");
        jButton2EuroStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EuroStockAActionPerformed(evt);
            }
        });

        jTextField2EuroS.setEditable(false);

        jButton1EuroStock1A.setText("+");
        jButton1EuroStock1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EuroStock1AActionPerformed(evt);
            }
        });

        jTextField1EuroS.setEditable(false);

        jButton50CentStockA.setText("+");
        jButton50CentStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentStockAActionPerformed(evt);
            }
        });

        jTextField50CentS.setEditable(false);

        jButton20CentStockA.setText("+");
        jButton20CentStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentStockAActionPerformed(evt);
            }
        });

        jTextField20CentS.setEditable(false);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("2 EURO");

        jLabel2.setText("1 EURO");

        jLabel3.setText("50 CENT");

        jLabel4.setText("20 CENT");

        jButton1EuroStockM.setText("-");
        jButton1EuroStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EuroStockMActionPerformed(evt);
            }
        });

        jButton50CentStockM.setText("-");
        jButton50CentStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentStockMActionPerformed(evt);
            }
        });

        jButton20CentStockM.setText("-");
        jButton20CentStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentStockMActionPerformed(evt);
            }
        });

        jButton2EuroStockM.setText("-");
        jButton2EuroStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EuroStockMActionPerformed(evt);
            }
        });

        jLabel5.setText("10 CENT");

        jButton10CentStockA.setText("+");
        jButton10CentStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10CentStockAActionPerformed(evt);
            }
        });

        jTextField10CentS.setEditable(false);

        jButton10CentStockM.setText("-");
        jButton10CentStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10CentStockMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jButton20CentStockA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField20CentS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton50CentStockA)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1EuroStock1A, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2EuroStockA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(38, 38, 38)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton1EuroStockM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2EuroStockM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton50CentStockM))
                                .addComponent(jButton20CentStockM)
                                .addComponent(jButton10CentStockM))
                            .addGap(36, 36, 36)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1EuroS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2EuroS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextField50CentS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton10CentStockA)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField10CentS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2EuroStockA)
                            .addComponent(jTextField2EuroS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1EuroStock1A)
                            .addComponent(jTextField1EuroS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton50CentStockA)
                            .addComponent(jTextField50CentS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton20CentStockA)
                            .addComponent(jTextField20CentS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton10CentStockA)
                            .addComponent(jTextField10CentS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2EuroStockM)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1EuroStockM)
                        .addGap(40, 40, 40)
                        .addComponent(jButton50CentStockM)
                        .addGap(40, 40, 40)
                        .addComponent(jButton20CentStockM)
                        .addGap(40, 40, 40)
                        .addComponent(jButton10CentStockM)))
                .addGap(45, 45, 45)
                .addComponent(jButtonClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // close frame 
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //set focus to close button 
        jButtonClose.requestFocus(true);
        // set textfields to stock of machine coins 
        jTextField2EuroS.setText(Integer.toString(coinStock[0]));
        jTextField1EuroS.setText(Integer.toString(coinStock[1]));
        jTextField50CentS.setText(Integer.toString(coinStock[2]));
        jTextField20CentS.setText(Integer.toString(coinStock[3]));
        jTextField10CentS.setText(Integer.toString(coinStock[4]));
    }//GEN-LAST:event_formWindowOpened

    private void jButton2EuroStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EuroStockAActionPerformed
        // set text field to 2 euro coin stock and add coin
        jTextField2EuroS.setText(AddCoin(0));
    }//GEN-LAST:event_jButton2EuroStockAActionPerformed

    private void jButton1EuroStock1AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EuroStock1AActionPerformed
        // set text field to 1 euro coin stock and add coin 
        jTextField1EuroS.setText(AddCoin(1));
    }//GEN-LAST:event_jButton1EuroStock1AActionPerformed

    private void jButton50CentStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentStockAActionPerformed
        // set text field to 50 cent coin stock and add coin  
        jTextField50CentS.setText(AddCoin(2));
    }//GEN-LAST:event_jButton50CentStockAActionPerformed

    private void jButton20CentStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentStockAActionPerformed
      // set text field to 20 cent coin stock and add coin 
        jTextField20CentS.setText(AddCoin(3));
    }//GEN-LAST:event_jButton20CentStockAActionPerformed

    private void jButton1EuroStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EuroStockMActionPerformed
       // set text field to 1 euro coin stock and minus coin
        jTextField1EuroS.setText(MinusCoin(1));
    }//GEN-LAST:event_jButton1EuroStockMActionPerformed

    private void jButton50CentStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentStockMActionPerformed
        // set text field to 50 cent coin stock and minus coin
        jTextField50CentS.setText(MinusCoin(2));
    }//GEN-LAST:event_jButton50CentStockMActionPerformed

    private void jButton20CentStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentStockMActionPerformed
        // set text field to 20 cent coin stock and minus coin
        jTextField20CentS.setText(MinusCoin(3));
    }//GEN-LAST:event_jButton20CentStockMActionPerformed

    private void jButton2EuroStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EuroStockMActionPerformed
       // set text field to 2 euro coin stock and minus coin
        jTextField2EuroS.setText(MinusCoin(0));
    }//GEN-LAST:event_jButton2EuroStockMActionPerformed

    private void jButton10CentStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10CentStockAActionPerformed
       // set text field to 10 cent coin stock and add coin
        jTextField10CentS.setText(AddCoin(4));
    }//GEN-LAST:event_jButton10CentStockAActionPerformed

    private void jButton10CentStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10CentStockMActionPerformed
        // set text field to 10 cent  coin stock and minus coin
        jTextField10CentS.setText(MinusCoin(4));
    }//GEN-LAST:event_jButton10CentStockMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMoneyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMoneyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMoneyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMoneyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMoneyFrame().setVisible(true);
            }
        });
    }
    // method for adding coins to stock and balance
    public static String AddCoin( int index){
        coinStock[index] += 1;
        balance += coinType[index];
        String parameter = (Integer.toString(coinStock[index]));
        return parameter;
        
    }
    // method for minusing coins from balance and coin stock 
    public static String MinusCoin( int index){
        // if coin in stock then minus one coin 
        if (coinStock[index] > 0 ) {
        coinStock[index] -= 1;
        balance -= coinType[index];
       
        } else {
            // if coin is 1 euro or 2 euro display error message
            if (coinType[index] >= 100){
            String formatCoin = String.format("%.0f", coinType[index]/100);
            JOptionPane.showMessageDialog(null, "No " + formatCoin + " euro coins available");
            //if coin is less than a euro display error message
            } else {
                String formatCoin = String.format("%.0f", coinType[index]);
                JOptionPane.showMessageDialog(null, "No " + formatCoin + " cent coins available");
            }
        }
        String parameter = (Integer.toString(coinStock[index]));
        return parameter;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10CentStockA;
    private javax.swing.JButton jButton10CentStockM;
    private javax.swing.JButton jButton1EuroStock1A;
    private javax.swing.JButton jButton1EuroStockM;
    private javax.swing.JButton jButton20CentStockA;
    private javax.swing.JButton jButton20CentStockM;
    private javax.swing.JButton jButton2EuroStockA;
    private javax.swing.JButton jButton2EuroStockM;
    private javax.swing.JButton jButton50CentStockA;
    private javax.swing.JButton jButton50CentStockM;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField10CentS;
    private javax.swing.JTextField jTextField1EuroS;
    private javax.swing.JTextField jTextField20CentS;
    private javax.swing.JTextField jTextField2EuroS;
    private javax.swing.JTextField jTextField50CentS;
    // End of variables declaration//GEN-END:variables
}
