/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.vendingMachine;

import javax.swing.JOptionPane;
import static my.vendingMachine.VendingMachineFrame.*;


/**
 *
 * @author ryan3
 */
public class AddStockFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddStockFrame
     */
    public AddStockFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCokeStockA = new javax.swing.JButton();
        jLabelCoke = new javax.swing.JLabel();
        jButtonFantaStockA = new javax.swing.JButton();
        jLabelFanta = new javax.swing.JLabel();
        jButton7UPStockA = new javax.swing.JButton();
        jLabel7UP = new javax.swing.JLabel();
        jLabelSprite = new javax.swing.JLabel();
        jButtonSpriteStockA = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonFantaStockM = new javax.swing.JButton();
        jButton7UPStockM = new javax.swing.JButton();
        jButtonSpriteStockM = new javax.swing.JButton();
        jButtonCokeStockM = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Stock");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonCokeStockA.setText("+ ");
        jButtonCokeStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCokeStockAActionPerformed(evt);
            }
        });

        jButtonFantaStockA.setText("+ ");
        jButtonFantaStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFantaStockAActionPerformed(evt);
            }
        });

        jButton7UPStockA.setText("+ ");
        jButton7UPStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7UPStockAActionPerformed(evt);
            }
        });

        jButtonSpriteStockA.setText("+ ");
        jButtonSpriteStockA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpriteStockAActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("Coke");

        jLabel2.setText("Fanta");

        jLabel3.setText("7UP");

        jLabel4.setText("Sprite");

        jButtonFantaStockM.setText("-");
        jButtonFantaStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFantaStockMActionPerformed(evt);
            }
        });

        jButton7UPStockM.setText("-");
        jButton7UPStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7UPStockMActionPerformed(evt);
            }
        });

        jButtonSpriteStockM.setText("-");
        jButtonSpriteStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpriteStockMActionPerformed(evt);
            }
        });

        jButtonCokeStockM.setText("-");
        jButtonCokeStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCokeStockMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFantaStockA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jButtonCokeStockA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7UPStockA, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jButtonSpriteStockA, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton7UPStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSpriteStockM, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonFantaStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCokeStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7UP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSprite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCoke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFanta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCokeStockA)
                            .addComponent(jLabelCoke, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFantaStockA)
                            .addComponent(jLabelFanta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7UPStockA)
                            .addComponent(jLabel7UP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSpriteStockA)
                            .addComponent(jLabelSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCokeStockM)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonFantaStockM)
                        .addGap(33, 33, 33)
                        .addComponent(jButton7UPStockM)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonSpriteStockM)))
                .addGap(29, 29, 29)
                .addComponent(jButtonClose)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCokeStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCokeStockAActionPerformed
        // set label to coke stock and add stock 
        jLabelCoke.setText(AddStock(0));
    }//GEN-LAST:event_jButtonCokeStockAActionPerformed

    private void jButtonFantaStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFantaStockAActionPerformed
        // set label to fanta stock and add stock 
        jLabelFanta.setText(AddStock(1));
    }//GEN-LAST:event_jButtonFantaStockAActionPerformed

    private void jButton7UPStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7UPStockAActionPerformed
        // set label to 7UP stock and add stock 
        jLabel7UP.setText(AddStock(2));
    }//GEN-LAST:event_jButton7UPStockAActionPerformed

    private void jButtonSpriteStockAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpriteStockAActionPerformed
        // set label to sprite stock and add stock 
        jLabelSprite.setText(AddStock(3));
    }//GEN-LAST:event_jButtonSpriteStockAActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       // set focus to close button on frame open 
        jButtonClose.requestFocus(true);
        // set labels to stock of products
        jLabelCoke.setText(Integer.toString(productStock[0]));
        jLabelFanta.setText(Integer.toString(productStock[1]));
        jLabel7UP.setText(Integer.toString(productStock[2]));
        jLabelSprite.setText(Integer.toString(productStock[3]));
        
    }//GEN-LAST:event_formWindowOpened

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // close frame 
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonFantaStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFantaStockMActionPerformed
        // set label to coke stock and minus stock 
        jLabelFanta.setText(MinusStock(1));
    }//GEN-LAST:event_jButtonFantaStockMActionPerformed

    private void jButton7UPStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7UPStockMActionPerformed
       // set label to 7UP stock and minus stock 
        jLabel7UP.setText(MinusStock(2));
    }//GEN-LAST:event_jButton7UPStockMActionPerformed

    private void jButtonSpriteStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpriteStockMActionPerformed
        // set label to sprite stock and minus stock 
        jLabelSprite.setText(MinusStock(3));
    }//GEN-LAST:event_jButtonSpriteStockMActionPerformed

    private void jButtonCokeStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCokeStockMActionPerformed
       // set label to coke stock and minus stock 
        jLabelCoke.setText(MinusStock(0));
    }//GEN-LAST:event_jButtonCokeStockMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStockFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStockFrame().setVisible(true);
            }
        });
    }
    // method to add stock 
    public static String AddStock( int index){
        productStock[index] += 1;
        String parameter = (Integer.toString(productStock[index]));
        return parameter;
        
    }
    // method for minusing stock 
     public static String MinusStock( int index){
       if (productStock[index] > 0){
        productStock[index] -= 1; 
        //display out of stock message 
        }   else {
           JOptionPane.showMessageDialog(null, productNames[index] + " is not in stock!");
       }
        String parameter = (Integer.toString(productStock[index]));
        return parameter;
     }
        
        
    
     

    
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7UPStockA;
    private javax.swing.JButton jButton7UPStockM;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonCokeStockA;
    private javax.swing.JButton jButtonCokeStockM;
    private javax.swing.JButton jButtonFantaStockA;
    private javax.swing.JButton jButtonFantaStockM;
    private javax.swing.JButton jButtonSpriteStockA;
    private javax.swing.JButton jButtonSpriteStockM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7UP;
    private javax.swing.JLabel jLabelCoke;
    private javax.swing.JLabel jLabelFanta;
    private javax.swing.JLabel jLabelSprite;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
