

package my.vendingMachine;

import javax.swing.JOptionPane;
import java.awt.Color;


/**
 *
 * @author ryan3
 */
public class VendingMachineFrame extends javax.swing.JFrame {
    
    //Declare variables/Arrays for names of products, sotck of products, price of products,
    //stock of coins, type of coins, machine balance and customer balance. 
    public static String productNames [] = new String [] {"Coke", "Fanta", "7up,", "Sprite"};
    public static int productStock [] = new int [] {3,3,3,3};    
    public static double productPrice [] = new double [] {250, 200, 175, 220};
    public static int coinStock [] = new int [] {5,5,5,5,5}; 
    public static double balance =  0;
    public static double coinType [] = new double [] {200, 100, 50, 20, 10};
    public static double customerBalance = 0.0;
    int counter [] = new int [] {0,0,0,0,0};
    
    // declare variables/array for cancel button ( balance, coin stock) 
    double cancelBalance = 0.0;
    int cancelCoinStock [] = new int [] {0,0,0,0,0};
    
    
    

    /**
     * Creates new form VendingMachineFrame
     */
    public VendingMachineFrame() {
        initComponents();
        getContentPane().setBackground(Color.RED); // Set background color
        
        // set Images for dispensing products to not - visible
        jLabelCoke.setVisible(false);
        jLabelFantaCan.setVisible(false);
        jLabel7UPCan.setVisible(false);
        jLabelSpriteCan.setVisible(false);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDispenseSprite = new javax.swing.JButton();
        jButtonDispense7UP = new javax.swing.JButton();
        jButtonDispenseCoke = new javax.swing.JButton();
        jButtonDispenseFanta = new javax.swing.JButton();
        jButton2Euro = new javax.swing.JButton();
        jButton1Euro = new javax.swing.JButton();
        jButton50Cent = new javax.swing.JButton();
        jButton20Cent = new javax.swing.JButton();
        jTextFieldBalance = new javax.swing.JTextField();
        jTextField2Euro = new javax.swing.JTextField();
        jTextField20Cent = new javax.swing.JTextField();
        jTextField50Cent = new javax.swing.JTextField();
        jTextField1Euro = new javax.swing.JTextField();
        jButtonAddStock = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jTextFieldFanta = new javax.swing.JTextField();
        jTextFieldCoke = new javax.swing.JTextField();
        jTextField7UP = new javax.swing.JTextField();
        jTextFieldSprite = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAddMoney = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCustomerBalance = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2EuroM = new javax.swing.JTextField();
        jTextField20CentM = new javax.swing.JTextField();
        jTextField50CentM = new javax.swing.JTextField();
        jTextField1EuroM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonReturn = new javax.swing.JButton();
        jTextField10Cent = new javax.swing.JTextField();
        jButton10Cent = new javax.swing.JButton();
        jTextField10CentM = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOutput = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabelCoke = new javax.swing.JLabel();
        jLabel7UPCan = new javax.swing.JLabel();
        jLabelFantaCan = new javax.swing.JLabel();
        jLabelSpriteCan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonDispenseSprite.setText("Sprite");
        jButtonDispenseSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDispenseSpriteActionPerformed(evt);
            }
        });

        jButtonDispense7UP.setText("7UP");
        jButtonDispense7UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDispense7UPActionPerformed(evt);
            }
        });

        jButtonDispenseCoke.setText("Coke");
        jButtonDispenseCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDispenseCokeActionPerformed(evt);
            }
        });

        jButtonDispenseFanta.setText("Fanta");
        jButtonDispenseFanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDispenseFantaActionPerformed(evt);
            }
        });

        jButton2Euro.setText("$2");
        jButton2Euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2EuroActionPerformed(evt);
            }
        });

        jButton1Euro.setText("$1");
        jButton1Euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EuroActionPerformed(evt);
            }
        });

        jButton50Cent.setText("$0.50");
        jButton50Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50CentActionPerformed(evt);
            }
        });

        jButton20Cent.setText("$0.20");
        jButton20Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20CentActionPerformed(evt);
            }
        });

        jTextFieldBalance.setEditable(false);
        jTextFieldBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBalanceActionPerformed(evt);
            }
        });

        jTextField2Euro.setEditable(false);

        jTextField20Cent.setEditable(false);

        jTextField50Cent.setEditable(false);

        jTextField1Euro.setEditable(false);

        jButtonAddStock.setText(" Stock");
        jButtonAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStockActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jTextFieldFanta.setEditable(false);

        jTextFieldCoke.setEditable(false);

        jTextField7UP.setEditable(false);

        jTextFieldSprite.setEditable(false);

        jButtonUpdate.setBackground(new java.awt.Color(255, 255, 0));
        jButtonUpdate.setText("Update ");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonAddMoney.setText("Float");
        jButtonAddMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMoneyActionPerformed(evt);
            }
        });

        jLabel1.setText("Machine Balance");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/Can Coke Small.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/Can Fanta Small.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/7UP Can Small.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/Sprite Can Small.png"))); // NOI18N

        jLabel6.setText("Customer Balance");

        jTextFieldCustomerBalance.setEditable(false);

        jButtonCancel.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonConfirm.setBackground(new java.awt.Color(51, 255, 0));
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jLabel7.setText("Customer Coins:");

        jTextField2EuroM.setEditable(false);

        jTextField20CentM.setEditable(false);

        jTextField50CentM.setEditable(false);

        jTextField1EuroM.setEditable(false);

        jLabel8.setText("Machine Coins:");

        jButtonReturn.setText("Return Change");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jTextField10Cent.setEditable(false);

        jButton10Cent.setText("$0.10");
        jButton10Cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10CentActionPerformed(evt);
            }
        });

        jTextField10CentM.setEditable(false);
        jTextField10CentM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10CentMActionPerformed(evt);
            }
        });

        jLabel9.setText("Drink Stock:");

        jLabel10.setText("Drink Price");

        jLabel11.setText("Coke");

        jLabel12.setText("Fanta");

        jLabel13.setText("7UP");

        jLabel14.setText("Sprite");

        jLabel15.setText("$2.50");

        jLabel16.setText("$2.00");

        jLabel17.setText("$1.75");

        jLabel18.setText("$2.20");

        jLabel19.setText("$2");

        jLabel20.setText("$1");

        jLabel21.setText("$0.50");

        jLabel22.setText("$0.20");

        jLabel23.setText("$0.10");

        jTextAreaOutput.setEditable(false);
        jTextAreaOutput.setBackground(new java.awt.Color(51, 255, 0));
        jTextAreaOutput.setColumns(20);
        jTextAreaOutput.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOutput);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(384, 170));
        jPanel1.setMinimumSize(new java.awt.Dimension(384, 170));
        jPanel1.setPreferredSize(new java.awt.Dimension(384, 170));

        jLabelCoke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/Can of Coke.png"))); // NOI18N

        jLabel7UPCan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/7UP Can.png"))); // NOI18N
        jLabel7UPCan.setText("jLabel24");
        jLabel7UPCan.setMaximumSize(new java.awt.Dimension(384, 170));
        jLabel7UPCan.setMinimumSize(new java.awt.Dimension(384, 170));
        jLabel7UPCan.setPreferredSize(new java.awt.Dimension(384, 170));

        jLabelFantaCan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/Fanta Can.png"))); // NOI18N
        jLabelFantaCan.setText("jLabel24");
        jLabelFantaCan.setMaximumSize(new java.awt.Dimension(384, 170));
        jLabelFantaCan.setMinimumSize(new java.awt.Dimension(384, 170));
        jLabelFantaCan.setPreferredSize(new java.awt.Dimension(384, 170));

        jLabelSpriteCan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/vendingMachine/Sprite Can.png"))); // NOI18N
        jLabelSpriteCan.setText("jLabel24");
        jLabelSpriteCan.setMaximumSize(new java.awt.Dimension(384, 170));
        jLabelSpriteCan.setMinimumSize(new java.awt.Dimension(384, 170));
        jLabelSpriteCan.setPreferredSize(new java.awt.Dimension(384, 170));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7UPCan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSpriteCan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFantaCan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCoke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCoke)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7UPCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFantaCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSpriteCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField50CentM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1EuroM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2EuroM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField20CentM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10CentM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField20Cent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10Cent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField50Cent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldCoke, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldFanta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField7UP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton20Cent))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton10Cent)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2Euro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1Euro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2Euro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1Euro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton50Cent))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(422, 422, 422))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAddMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addComponent(jLabel2))
                                                .addComponent(jButtonDispenseCoke))
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addComponent(jLabel3))
                                                .addComponent(jButtonDispenseFanta))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addComponent(jLabel4))
                                                .addComponent(jButtonDispense7UP))
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonDispenseSprite)
                                                .addComponent(jLabel5))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldCustomerBalance, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(jTextFieldBalance, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDispenseFanta)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDispense7UP)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDispenseSprite)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonReturn)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonConfirm)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButtonCancel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2Euro)
                                            .addComponent(jTextField2Euro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1Euro, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField1Euro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField50Cent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton50Cent))))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField20Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton20Cent))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField10Cent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton10Cent))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldFanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField7UP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel17))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel18)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDispenseCoke)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(238, 238, 238)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField2EuroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1EuroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField50CentM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField20CentM, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField10CentM, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldCustomerBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(jButtonClose))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonAddStock)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAddMoney)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonUpdate))))
                            .addGap(2, 2, 2))))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2EuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2EuroActionPerformed
       // call addcoin method, for inseting 2 euro coin
        AddCoin(2, 0);
       
      // set jtextfield to 2 euro customer coin
        jTextField2Euro.setText(Integer.toString(cancelCoinStock[0]));
         
    }//GEN-LAST:event_jButton2EuroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // direct focus onto close button at start of application
        jButtonClose.requestFocus(true);
        
        //set jtextfields to customer coins
        jTextField2Euro.setText(Integer.toString(cancelCoinStock[0]));
        jTextField1Euro.setText(Integer.toString(cancelCoinStock[1]));
        jTextField50Cent.setText(Integer.toString(cancelCoinStock[2]));
        jTextField20Cent.setText(Integer.toString(cancelCoinStock[3]));
        jTextField10Cent.setText(Integer.toString(cancelCoinStock[4]));
        
        //set jtextfields to stock of different products
        jTextFieldCoke.setText(Integer.toString(productStock[0]));
        jTextFieldFanta.setText(Integer.toString(productStock[1]));
        jTextField7UP.setText(Integer.toString(productStock[2]));
        jTextFieldSprite.setText(Integer.toString(productStock[3]));
        
        // set balance to amount of coins in stock multiplied by coin type ( in cent)
        balance = ((coinStock[0]) * (coinType[0]) + (coinStock[1]) * (coinType[1]) + (coinStock[2]) * (coinType[2]) + (coinStock[3]) * (coinType[3]) + (coinStock[4]) * (coinType[4]));
        // format balance to 2 decimal places
        String balanceFormat = String.format("%.2f", balance / 100);
        //set jtextfield to balance
        jTextFieldBalance.setText(balanceFormat + " Euro");
        //format customer balance to 2 deciaml places
        String customerBalanceFormat = String.format("%.2f", customerBalance / 100);
        // set jtextfield to customer balance
        jTextFieldCustomerBalance.setText(customerBalanceFormat + " Euro");
        
        // set jtexfields to machine coin stock
        jTextField2EuroM.setText(Integer.toString(coinStock[0]));
        jTextField1EuroM.setText(Integer.toString(coinStock[1]));
        jTextField50CentM.setText(Integer.toString(coinStock[2]));
        jTextField20CentM.setText(Integer.toString(coinStock[3]));
        jTextField10CentM.setText(Integer.toString(coinStock[4]));
    }//GEN-LAST:event_formWindowOpened
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void jButton1EuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EuroActionPerformed
        // call addcoin method, for inseting 1 euro coin
        AddCoin(1, 1);
        
        //set jtextfield to 1 euro customer coin 
        jTextField1Euro.setText(Integer.toString(cancelCoinStock[1]));
    }//GEN-LAST:event_jButton1EuroActionPerformed

    private void jButton50CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50CentActionPerformed
        // call addcoin method, for inseting 50 cent coin
        AddCoin(0.5, 2);
        
        //set jtextfield to 50 cent customer coin  
        jTextField50Cent.setText(Integer.toString(cancelCoinStock[2]));
    }//GEN-LAST:event_jButton50CentActionPerformed

    private void jButton20CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20CentActionPerformed
        // call addcoin method, for inseting  20 cent coin
        AddCoin(0.2, 3);
        
        //set jtextfield to 20 cent customer coin
        jTextField20Cent.setText(Integer.toString(cancelCoinStock[3]));
    }//GEN-LAST:event_jButton20CentActionPerformed

    private void jButtonAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStockActionPerformed
        // open add stock frame
        AddStockFrame ASF = new AddStockFrame();
        ASF.setVisible(true);
    }//GEN-LAST:event_jButtonAddStockActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
       // close frame
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonDispenseCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDispenseCokeActionPerformed
        // call method setting all product images to false
        SetCanLabelToFalse();
        
        // if coke is in stock and customer balance is greater than price of coke than set coke image to visible
        if ((productStock[0] > 0) && (customerBalance >= productPrice[0])) {
        jLabelCoke.setVisible(true);
        } 
        
        // call dispense method 
        Dispense(0);
       

    }//GEN-LAST:event_jButtonDispenseCokeActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
      // call update method
      Update();
      
      // output machine updated in text area
      jTextAreaOutput.setText("Machine Updated");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBalanceActionPerformed

    private void jButtonAddMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMoneyActionPerformed
        // open add money frame
        AddMoneyFrame AMF = new AddMoneyFrame();
        AMF.setVisible(true);
    }//GEN-LAST:event_jButtonAddMoneyActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // if cancel balance is bigger or equal than 100 cent divide by 100 (change to euro) than format to 2 decimal places and output message
        if (cancelBalance >= 100) {
        cancelBalance = cancelBalance / 100;
        String formatCB = String.format("%.2f", cancelBalance);
        JOptionPane.showMessageDialog(null, "The Balance of " + formatCB + " euro has been returned to you!");
        } else {
        // else if cancel balance is less than 100 format to 0 decimal places and output message ( keep in cent)
        String formatCB = String.format("%.0f", cancelBalance);
        JOptionPane.showMessageDialog(null, "The Balance of " + formatCB + " cent has been returned to you!");
        }
        
        // set cancel balance back to 0
        cancelBalance = 0.0;
        // set customer coin stock to 0
        SetCancelCoinStockTo0();
        // set counter for coins dispensed to 0
        SetCounterTo0();
        // set text area to blank
        jTextAreaOutput.setText("");
        // call update method
        Update();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // add customer coins isnerted into machine balance
        balance += cancelBalance;
        // add customer coins inserted into custoemr balance
        customerBalance += cancelBalance;
        
        //add customer coins inserted to machine coins
        coinStock[0] += cancelCoinStock[0];
        coinStock[1] += cancelCoinStock[1];
        coinStock[2] += cancelCoinStock[2];
        coinStock[3] += cancelCoinStock[3];
        coinStock[4] += cancelCoinStock[4];
        
        //set cancel balance to 0
        cancelBalance = 0.0;
        
        // set cancel coin sttock to 0
        SetCancelCoinStockTo0();
        
        // set counter for amount of coins added to 0
        SetCounterTo0();
        
        // set text area to blank
        jTextAreaOutput.setText("");
        
        // call update method
        Update();
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButtonDispenseFantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDispenseFantaActionPerformed
        // call method setting all product images to false
        SetCanLabelToFalse();
        
         // if fanta is in stock and customer balance is greater than price of fanta than set coke image to visible
        if ((productStock[1] > 0) && (customerBalance >= productPrice[1])) {
        jLabelFantaCan.setVisible(true);
        } 
       // call dispense method
        Dispense(1);
    }//GEN-LAST:event_jButtonDispenseFantaActionPerformed

    private void jButtonDispense7UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDispense7UPActionPerformed
       // call method setting all product images to false
        SetCanLabelToFalse();
        
         // if 7up is in stock and customer balance is greater than price of coke than set 7up image to visible
        if ((productStock[2] > 0) && (customerBalance >= productPrice[2])) {
        jLabel7UPCan.setVisible(true);
        } 
        
        //call dispense method
        Dispense(2);
    }//GEN-LAST:event_jButtonDispense7UPActionPerformed

    private void jButtonDispenseSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDispenseSpriteActionPerformed
        // call method setting all product images to false
        SetCanLabelToFalse();
        
         // if sprite is in stock and customer balance is greater than price of sprite than set coke image to visible
        if ((productStock[3] > 0) && (customerBalance >= productPrice[3])) {
        jLabelSpriteCan.setVisible(true);
        } 
        
        // call dispense method
        Dispense(3);
    }//GEN-LAST:event_jButtonDispenseSpriteActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // if customer balance is bigger than or equal to 100 cent format customer balance to 2 deciaml places and divide by 100 (convert to euro), output change message 
        if (customerBalance >= 100) {
        String formatCB = String.format("%.2f", customerBalance / 100);
        JOptionPane.showMessageDialog(null, "Your Change is " + formatCB + " Euro");
        
        // if customer balance is less than 100 cent format to 0 decimal places and output change message
        } else {
        String formatCB = String.format("%.0f", customerBalance);
        JOptionPane.showMessageDialog(null, "Your Change is " + formatCB + " Cent");
        }
        // take customer balance from balance
        balance -= customerBalance;
        // decalare variable and set it equal to customer balance for use in while loop
        double customerBalance2 = customerBalance;
        // set customer balance to 0
        customerBalance = 0;
        // declare variable for remaining balance (used in loop)
        double remainingBalance = 0;
        // declare array coin counter for amount of coins returned to customer
        int coinCounter[] = new int [] {0,0,0,0,0};
      
         // loop continues until customerbalance2 is 0 or less
        while (customerBalance2 > 0) {
            // if customerbalance2 is bigger or equal to 200 cent and 2 euro coins are in stock enter statment
            if ((customerBalance2 >= 200) && (coinStock[0] > 0)){
                //2 euro coin stock minus 1 
                coinStock[0] -= 1;
                // customer balance -200 cent
                customerBalance2 -= 200;
                // 2 euro coin counter + 1
                coinCounter[0] += 1;
             // if customerbalance2 is bigger or equal to 100 cent and 1 euro coins are in stock enter statment   
            } else if ((customerBalance2 >= 100) && (coinStock[1] > 0)) {
                // 1 euro coin stock minus 1
                coinStock[1] -= 1;
                // customer balance2 - 100 cent
                customerBalance2-= 100;
                // 1 euro coin counter + 1
                coinCounter[1] += 1;
             // if customerbalance2 is bigger or equal to 50 cent and 50 cent coins are in stock enter statment   
            } else if ((customerBalance2 >= 50) && (coinStock[2] > 0)) {
                // 50 cent coin stock - 1 
                coinStock[2] -= 1;
                // cusomer balance2 - 50 cent
                customerBalance2 -= 50;
                // 50 cent coin counter + 1
                coinCounter[2] += 1;
             // if customerbalance2 is bigger or equal to 20 cent and 20 cent coins are in stock enter statment
            } else if ((customerBalance2 >= 20) && (coinStock[3] > 0)) {
                // 20 cent coin stock - 1
                coinStock[3] -= 1;
                // customer balance - 20 cent
                customerBalance2 -= 20;
                // 20 cent coin counter + 1
                coinCounter[3] += 1;
             // if customerbalance2 is bigger or equal to 10 cent and 10 cent coins are in stock enter statment
            } else if ((customerBalance2 >= 10) && (coinStock[4] > 0)) {
                //  10 cent coin stock - 1
                coinStock[4] -= 1;
                // custoemrbalance 2- 10 cent 
                customerBalance2 -= 10;
                // 10 cent coin counter + 1
                coinCounter[4] += 1;
               
            } else {
                // if customerbalance is less than 10 cent enter statement
                if (customerBalance2 < 10) {
                // set remainingbalance = customer balance to update customer balance if 5 cent is remaining or no coins in machine
                remainingBalance = customerBalance2;
                //format customer balance to 2 deciaml places and output message telling user no 5 cent coins in machine 
                String formatCB2 = String.format("%.0f", customerBalance2);
                JOptionPane.showMessageDialog(null, "No 5 cent coins available, please contact the vending machine provider!\nThe remaining balance is " + formatCB2 + " cent.");
                //set customerbalance2 to 0 to exit while loop
                customerBalance2= 0;
                } else {
                // divide customer balance by 100 (connvert to euro)
                customerBalance2 = customerBalance2 / 100;
                // format customerbalance to 2 decimal places and output message saying no coins in machine
                String formatCB2 = String.format("%.2f", customerBalance2);
                JOptionPane.showMessageDialog(null, "No coins in machine that match your change, please contact the vending machine provider!\nThe remaining change owed is " + formatCB2 + " euro");
                // multipy customerbalance2 100 and set to remaining balance 
                remainingBalance = customerBalance2 * 100 ;
                //set customerbalance2 to 0 to exit while loop
                customerBalance2= 0;
                }
            
            }
            // set customer balance to remaing balance(balance nnot returned to user)
            customerBalance = remainingBalance ;
            //  add remaing balance not returned to user back to machine balance
            balance += remainingBalance;
        }
        // output to text area amount of coins returned to user
        jTextAreaOutput.setText(coinType[0]/100 + " Euro X " + coinCounter[0] + " Dispensed" + "\n" + coinType[1]/100 + " Euro X " + coinCounter[1] + " Dispensed" + "\n"
                    + coinType[2]  + " Cent X " + coinCounter[2] + " Dispensed" + "\n" + coinType[3] + " Cent X " + coinCounter[3] + " Dispensed" + "\n" + coinType[4]   + " Cent X " + coinCounter[4] + " Dispensed");
        // call update method
        Update();
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButton10CentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10CentActionPerformed
        // call addcoin method, for inseting 10 cent coin
        AddCoin(0.1, 4);
        
        //set jtextfield to 10 cent customer coin
        jTextField10Cent.setText(Integer.toString(cancelCoinStock[4]));
    }//GEN-LAST:event_jButton10CentActionPerformed

    private void jTextField10CentMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10CentMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10CentMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         
//  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachineFrame().setVisible(true);
                
                
            }
        });
    }
    // method for adding coins to machine, updates cancel balence, counter, cancel coin stock
    public void AddCoin (double coin, int index) {
        cancelBalance += coin *100;
        counter[index] += 1;
        cancelCoinStock[index] += 1;
        //set text area to number of coins inserted
        if (coinType[index] >= 100) {
        jTextAreaOutput.setText((coinType[index]/100) + " Euro Inserted X " + counter[index]);
        } else {
        jTextAreaOutput.setText((coinType[index]) + " cent Inserted X " + counter[index]);
        }
    }
    //  method for dispensing a product
    public void Dispense (int index){
        // if product is in stock and balance is greater than product price minus stock and take away price from balance
        if (productStock[index] > 0  ){
            if (customerBalance >= productPrice[index]){
                productStock[index] -= 1;
                customerBalance -= productPrice[index];
                Update();
                jTextAreaOutput.setText(productNames[index] + " Dispensed");
            } else {
                CustomerBalanceError();
            }
        } else {
            StockError();
        }
    }
    // method for displaying a out of stock message
    public void StockError () {
        JOptionPane.showMessageDialog(null, "Not enough Stock in Machine!");
    }
    // methid for displaying not enough funds error message
     public void CustomerBalanceError () {
        JOptionPane.showMessageDialog(null, "Not enough money inserted into Machine!");
    }
     
     // method for updating jtexfields for stock, customer coins, machine coins and balances
     public void Update () {
        jTextFieldCoke.setText(Integer.toString(productStock[0]));
        jTextFieldFanta.setText(Integer.toString(productStock[1]));
        jTextField7UP.setText(Integer.toString(productStock[2]));
        jTextFieldSprite.setText(Integer.toString(productStock[3]));
        jTextField2EuroM.setText(Integer.toString(coinStock[0]));
        jTextField1EuroM.setText(Integer.toString(coinStock[1]));
        jTextField50CentM.setText(Integer.toString(coinStock[2]));
        jTextField20CentM.setText(Integer.toString(coinStock[3]));
        jTextField10Cent.setText(Integer.toString(coinStock[4]));
        jTextField10CentM.setText(Integer.toString(coinStock[4]));
        jTextField2Euro.setText(Integer.toString(cancelCoinStock[0]));
        jTextField1Euro.setText(Integer.toString(cancelCoinStock[1]));
        jTextField50Cent.setText(Integer.toString(cancelCoinStock[2]));
        jTextField20Cent.setText(Integer.toString(cancelCoinStock[3]));
        jTextField10Cent.setText(Integer.toString(cancelCoinStock[4]));
        String balanceFormat = String.format("%.2f", balance / 100);
        jTextFieldBalance.setText(balanceFormat + " Euro");
        String customerBalanceFormat = String.format("%.2f", customerBalance / 100);
        jTextFieldCustomerBalance.setText(customerBalanceFormat + " Euro");
        
     }
    
  
     // method for setting cancel coin stock back to 0
     public void SetCancelCoinStockTo0 (){
        cancelCoinStock[0] = 0;
        cancelCoinStock[1] = 0;
        cancelCoinStock[2] = 0;
        cancelCoinStock[3] = 0;
        cancelCoinStock[4] = 0;
     }
     // method for setting counters to 0
     public void SetCounterTo0 (){
         counter[0] = 0;
         counter[1] = 0;
         counter[2] = 0;
         counter[3] = 0;
         counter[4] = 0;
     }
     // method for setting product images to non - visible 
     public void SetCanLabelToFalse (){
         jLabelCoke.setVisible(false);
        jLabelFantaCan.setVisible(false);
        jLabel7UPCan.setVisible(false);
        jLabelSpriteCan.setVisible(false);
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10Cent;
    private javax.swing.JButton jButton1Euro;
    private javax.swing.JButton jButton20Cent;
    private javax.swing.JButton jButton2Euro;
    private javax.swing.JButton jButton50Cent;
    private javax.swing.JButton jButtonAddMoney;
    private javax.swing.JButton jButtonAddStock;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonDispense7UP;
    private javax.swing.JButton jButtonDispenseCoke;
    private javax.swing.JButton jButtonDispenseFanta;
    private javax.swing.JButton jButtonDispenseSprite;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel7UPCan;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCoke;
    private javax.swing.JLabel jLabelFantaCan;
    private javax.swing.JLabel jLabelSpriteCan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOutput;
    private javax.swing.JTextField jTextField10Cent;
    private javax.swing.JTextField jTextField10CentM;
    private javax.swing.JTextField jTextField1Euro;
    private javax.swing.JTextField jTextField1EuroM;
    private javax.swing.JTextField jTextField20Cent;
    private javax.swing.JTextField jTextField20CentM;
    private javax.swing.JTextField jTextField2Euro;
    private javax.swing.JTextField jTextField2EuroM;
    private javax.swing.JTextField jTextField50Cent;
    private javax.swing.JTextField jTextField50CentM;
    private javax.swing.JTextField jTextField7UP;
    private javax.swing.JTextField jTextFieldBalance;
    private javax.swing.JTextField jTextFieldCoke;
    private javax.swing.JTextField jTextFieldCustomerBalance;
    private javax.swing.JTextField jTextFieldFanta;
    private javax.swing.JTextField jTextFieldSprite;
    // End of variables declaration//GEN-END:variables
}
